"""baseline schema

Revision ID: a014d36df46e
Revises: 
Create Date: 2026-08-23 12:10:27.502274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a014d36df46e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doctor_id_email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hospital', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_doctor_id_email'), 'doctors', ['doctor_id_email'], unique=True)
    op.create_table('email_otps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_table('hospitals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.Column('emergency_ward', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doctor_id_email', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_doctor_id_email'), 'otps', ['doctor_id_email'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lifeverra_id', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=True),
    sa.Column('guardian_phone', sa.String(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('chronic_diseases', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('past_surgeries', sa.Text(), nullable=True),
    sa.Column('medical_verified', sa.Boolean(), nullable=True),
    sa.Column('medical_verified_by', sa.String(), nullable=True),
    sa.Column('medical_verified_hospital', sa.String(), nullable=True),
    sa.Column('medical_verified_role', sa.String(), nullable=True),
    sa.Column('medical_verified_at', sa.DateTime(), nullable=True),
    sa.Column('ai_cross_checked', sa.Boolean(), nullable=True),
    sa.Column('ai_cross_checked_at', sa.DateTime(), nullable=True),
    sa.Column('ai_cross_checked_source', sa.String(), nullable=True),
    sa.Column('qr_setup_seen', sa.Boolean(), nullable=True),
    sa.Column('medical_edit_history', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_accuracy_m', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), nullable=True),
    sa.Column('lock_screen_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=True)
    op.create_index(op.f('ix_patients_google_sub'), 'patients', ['google_sub'], unique=True)
    op.create_index(op.f('ix_patients_lifeverra_id'), 'patients', ['lifeverra_id'], unique=True)
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=True)
    op.create_table('access_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('doctor_email', sa.String(), nullable=True),
    sa.Column('access_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_hint', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('complaint_ref', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('doctor_email_reported', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_ref')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('triage_level', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('recommended_hospital_id', sa.String(), nullable=True),
    sa.Column('recommended_hospital_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_facilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=True),
    sa.Column('icu', sa.Boolean(), nullable=True),
    sa.Column('cardiology', sa.Boolean(), nullable=True),
    sa.Column('cardiac_icu', sa.Boolean(), nullable=True),
    sa.Column('cath_lab', sa.Boolean(), nullable=True),
    sa.Column('trauma_center', sa.Boolean(), nullable=True),
    sa.Column('neurology', sa.Boolean(), nullable=True),
    sa.Column('pediatrics', sa.Boolean(), nullable=True),
    sa.Column('maternity', sa.Boolean(), nullable=True),
    sa.Column('blood_bank', sa.Boolean(), nullable=True),
    sa.Column('dialysis', sa.Boolean(), nullable=True),
    sa.Column('ambulance', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_table('patient_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_documents')
    op.drop_table('hospital_facilities')
    op.drop_table('emergency_events')
    op.drop_table('emergency_contacts')
    op.drop_table('complaints')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_lifeverra_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_google_sub'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_otps_doctor_id_email'), table_name='otps')
    op.drop_table('otps')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_table('email_otps')
    op.drop_index(op.f('ix_doctors_doctor_id_email'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
